### ISSUE TITLE
Response not caching

### ISSUE THREAD

**Issue by limzykenneth** [airesvsg/wp-rest-api-cache#1]
Hi, I see this is quite a new plugin but it's just what I needed at the moment, so thanks!

However, the plugin doesn't seem to be working for me. My setup is that I have one domain and server hosting the wordpress site setup with the REST API and also with this plugin installed, and I have another domain and server hosting a frontend site that make GET request calls to the wordpress site for json data and I want that data to be cached.

I'm still developing the frontend locally at the moment and it's not cache the data. Am I missing some steps or something? Thanks again.

**Comment by airesvsg** [comment]
Hi @limzykenneth,
The plugin check if something is cached, otherwise it will not continue with all the processes to obtain the data.
The constant **WP_DEBUG** is active?
Thanks

**Comment by limzykenneth** [comment]
@airesvsg Sorry, been quite awhile since I used wordpress. Does that mean that this plugin does not set the header for the request asking for the client to cache the results?

**Comment by airesvsg** [comment]
Hi @limzykenneth,
I'll release a new version today with this feature.

**wp-content/plugins/wp-rest-api-cache/class-wp-rest-cache.php : 60**
```PHP
if ( $server instanceof WP_REST_Server ) {
	$headers = apply_filters( 'rest_cache_headers', array(), $request_uri, $server, $request );
	if ( ! empty( $headers ) ) {
		$server->send_headers( $headers );
	}
}
````

**wp-content/themes/my-theme/functions.php**
```PHP
add_filter( 'rest_cache_headers', function() {
	return array( 'Cache-Control' => 'max-age=3600' );
} );
```

**Comment by airesvsg** [comment]
Hi @limzykenneth,
I updated the plugin.
Thanks

**Comment by limzykenneth** [comment]
Seems to be caching now! Thanks.
