### ISSUE TITLE
Uncaught Exception: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by sarukuku** [airesvsg/wp-rest-api-cache#10]
I'm getting this kind of error just by installing & enabling the plugin:
```
[21-Mar-2017 08:46:03 UTC] PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in [].../wordpress/wp-includes/functions.php:435
Stack trace:
#0 [...]/wordpress/wp-includes/functions.php(435): serialize(Object(WP_REST_Response))
#1 [...]/wordpress/wp-includes/option.php(427): maybe_serialize(Object(WP_REST_Response))
#2 [...]/wordpress/wp-includes/option.php(730): add_option('_transient_rest...', Object(WP_REST_Response), '', 'no')
#3 [...]/dm-collection/plugins/wp-rest-api-cache/class-wp-rest-cache.php(63): set_transient('rest_cache_/wp-...', Object(WP_REST_Response), 3600)
#4 [...]/wordpress/wp-includes/class-wp-hook.php(298): WP_REST_Cache::pre_dispatch(Object(WP_REST_Response), Object(WP_REST_Server in [].../wordpress/wp-includes/functions.php on line 435
```

Any idea what's wrong?

**Comment by sarukuku** [comment]
I looked into this a bit and it seems that you can't serialize the `WP_REST_Response` object. If I change the [line 63](https://github.com/airesvsg/wp-rest-api-cache/blob/master/class-wp-rest-cache.php#L63) to
```php
set_transient( $key, $result->get_data(), $timeout );
```
then it works. But I'm not sure if the type returned will always be an instance of `WP_REST_Response` object so I can't really say if this is a viable option as a fix.

**Comment by sarukuku** [comment]
I created to pull request that fixes this. See #11.

**Comment by sarukuku** [comment]
I did a bit of testing & prototyping related to this issue and the pull request (#11) I submitted. It turned out that it's quite hard to try to get around the closure serialization issue inside the WP_REST_Response. I couldn't find any sane way to do it.

I tracked down where the closures were that were failing the serialization and the closures ended up being the validation and sanitation functions attached to the register_rest_route() function. Changing from using closures in those calls to using local named functions circumvents the serialization problem.

Using the closures in that way wasn't even my idea but actually a recommended way of doing it while the WP API wasn't yet in the core. See f.ex. the validate_callback example [here](http://v2.wp-api.org/extending/adding/).

I suggest that we add some note about not supporting closures inside the callback functions tied to the register_rest_route() function to the readme of this. Maybe it will save time from people who also  have the same problem. What do you think?

I'll also drop the PR related to this issue.

**Comment by airesvsg** [comment]
Hi @sarukuku,
Thanks for your time.
Please, send me more information about your environment like WP version, plugins, PHP version and endpoints.

Thanks

**Comment by sarukuku** [comment]
Sorry about the delay. I'm using the latest WP version and the problem is repeatable with only the wp-rest-api-cache plugin installed and active. I'm using PHP 7 and a sample endpoint that causes the error could look f.ex. like this:

```php
add_action( 'rest_api_init', function () {
	register_rest_route( 'myplugin/v1', '/author/(?P<id>\d+)', array(
		'methods' => 'GET',
		'callback' => 'my_awesome_func',
		'args' => array(
			'id' => array(
				'validate_callback' => function($param, $request, $key) {
					return is_numeric( $param );
				}
			),
		),
	) );
} );
```

The problem is that with PHP you can't serialize anonymous functions without tricks and the plugin relies on serialization on a level where an endpoint written like the one above would be serialized. As it includes an anonymous function it will throw an error when the plugin tries to serialize it for caching.

The way around this is to give the function a name and only reference it by name from the endpoint. It's an easy fix but I think it should be stated in the readme and handled gracefully in inside the plugin.

**Comment by wrux** [comment]
It looks like this is over a year old but did this get updated? I just tested the extension and got this error

**Comment by wrux** [comment]
This was using the default WP rest API on the latest version

**Comment by XedinUnknown** [comment]
Same problem.

**Comment by sarukuku** [comment]
Hans someone looked if the OTB WP REST API endpoints use inline functions in validation etc.? If this is the case this plugin will not work with them. At least that's my experience.
