### ISSUE TITLE
Caching Custom Endpoints

### ISSUE THREAD

**Issue by thame** [airesvsg/wp-rest-api-cache#17]
I have modified my theme's functions.php to allow an unlimited maximum number of posts. My API call is: 'wp-json/wp/v2/posts?page=1&per_page=1000'

My functions.php modification is:
```PHP
add_filter( 'rest_endpoints', function( $endpoints ){
    if ( ! isset( $endpoints['/wp/v2/posts'] ) ) {
        return $endpoints;
    }
    unset( $endpoints['/wp/v2/posts'][0]['args']['per_page']['maximum'] );
    return $endpoints;
});
```

The caching function is working great, substantially reducing load times as expected! The issue I'm having is that for unclear reasons and after anywhere from 4-24 hours, the served cached file no stops including all posts and reverts to serving only the most recent 10 posts (as if the per_page parameter were ignored).

I am currently solving the issue by emptying the cache, after which it resumed working as expected. I've tried the following steps without success:
- Changed cache time
- Changed API call (removing "page=1")

My current solution is to regularly monitor the cached file and manually empty the cache when I note that it is no longer serving the full number of posts. Any ideas on what might be going on?

**Comment by airesvsg** [comment]
Hi @thame,

Please, use the filter `rest_cache_timeout` to change the duration of cache.

 How to use:
```PHP
add_filter( 'rest_cache_timeout', function( $timeout ) {
  // https://codex.wordpress.org/Easier_Expression_of_Time_Constants
  return MONTH_IN_SECONDS;
} );
```

https://github.com/airesvsg/wp-rest-api-cache/blob/master/class-wp-rest-cache.php#L61

Thanks

**Comment by thame** [comment]
Thanks for the help!
