### ISSUE TITLE
POST requests have cache !

### ISSUE THREAD

**Issue by lxsjvln** [airesvsg/wp-rest-api-cache#19]
Hello,
My POST requests have cache, so how do you disable the cache for POST requests but not for GET requests on the URL wp-json/wp/v2/comments
thanks you
Your plugin is amazing !

**Comment by airesvsg** [comment]
Hello @lxsjvln,
Please, use the code below:
```PHP
add_filter( 'rest_cache_skip', function( $skip, $request_uri, $server, $request ) {
  if ( ! $skip && false !== stripos( $request_uri, 'wp-json/wp/v2/comments' ) && WP_REST_Server::CREATABLE === $request->get_method() ) {
    return true;
  }

  return $skip;
}, 10, 4 );
```

Thanks

**Comment by lxsjvln** [comment]
Thanks

**Comment by novogrammer** [comment]
This issue also occurs in ajax mail form with POST request.

At the second time, It returns
`{"status":"mail_sent"}`
,but not actually sent.

https://wordpress.org/plugins/contact-form-7/
