### ISSUE TITLE
Disable cache for custom routes

### ISSUE THREAD

**Issue by mnguye08** [airesvsg/wp-rest-api-cache#2]
Hi @airesvsg,

I use "wp-rest-api-cache" plugin and I would like to disable the cache specifically for a custom route (using register_rest_route() method).
Is there a way to do that?

Thanks

**Comment by airesvsg** [comment]
Hi @mnguye08,
yes, it's possible.

In below code I disabled for the all ACF route. 
```PHP
add_filter( 'rest_cache_skip', function( $skip, $uri ) {
	if ( ! $skip && strpos( $uri, 'acf/v2' ) !== false ) {
		$skip = true;
	}

	return $skip;
}, 10, 2 );
```

Thanks

**Comment by mnguye08** [comment]
Thanks @airesvsg!

**Comment by shez1983** [comment]
@airesvsg can you tell me where to place this code? i tried in my functions.php and placed a var_dump to see if it is working but it didnt?
