### ISSUE TITLE
cache woocommerce rest api v3 with products updated weekly: how to?

### ISSUE THREAD

**Issue by matteoraggi** [airesvsg/wp-rest-api-cache#3]
Hi, I need to cache the rest api v3 of woocommerce. The products are updated weekly and I need to cache the woocommerce rest api v3 because it is used from the android and ios app to read the products to show and they are loading very slowly: it need about 1 second for each product to load. I think that caching the results should show these result faster.

**Comment by airesvsg** [comment]
Hi @matteoraggi,
The REST API v3 of WooCommerce not use the WordPress REST API structure.
Thanks
