### ISSUE TITLE
Is this just browser-level caching?

### ISSUE THREAD

**Issue by axelson** [airesvsg/wp-rest-api-cache#4]
I'm not seeing any noticeable speed improvements using this plugin, is this just browser level caching or does it persist something to disk/mysql to speed up future requests for the same data?

**Comment by airesvsg** [comment]
Hi @axelson,
both.

Disk: https://github.com/airesvsg/wp-rest-api-cache/blob/master/class-wp-rest-cache.php#L54 
Browser: https://github.com/airesvsg/wp-rest-api-cache/blob/master/class-wp-rest-cache.php#L43

Thanks
