### ISSUE TITLE
not working with WP REST API V2

### ISSUE THREAD

**Issue by redprogrammer** [airesvsg/wp-rest-api-cache#5]
Plugin not working on WP REST API V2 posts query with parameter _embed.

for example: http://example.com/wp-json/wp/v2/posts?_embed

**Comment by airesvsg** [comment]
Hi @redprogrammer,
is **DEBUG_MODE** enabled?

**Comment by redprogrammer** [comment]
Hi @airesvsg 
DEBUG_MODE is not enabled
Thanks

**Comment by airesvsg** [comment]
Hi @redprogrammer,
It's works fine for me.

Steps of my test:
1- I accessed the url: `http://example.com/wp-json/wp/v2/posts?_embed`
2- I activated the plugin;
3- I accessed the url: `http://example.com/wp-json/wp/v2/posts?_embed`
4- I edited the title;
5- I accessed the url: `http://example.com/wp-json/wp/v2/posts?_embed`
6- I accessed the url: `http://example.com/wp-json/wp/v2/posts`

Thanks

![title-1](https://cloud.githubusercontent.com/assets/396668/21077236/03e93744-bf2c-11e6-80b1-f606b6df735a.JPG)
![title-2](https://cloud.githubusercontent.com/assets/396668/21077237/03ebfce0-bf2c-11e6-9b15-2857dff34b77.JPG)

**Comment by redprogrammer** [comment]
can you check the one post child _embeded and wp:featuremedia child??

data[0]._embedded['wp:featuredmedia'][0].source_url normally take me the media url of the data but after install the plugin the content changes?

Can you compare the responses with activate/deactivate the plugin please??
compare parts should be response sizes, response post _embeded parts

Thanks

**Comment by airesvsg** [comment]
Ok, I'll check.
When the plugin is deactivated, all cache are cleaned.

**Comment by redprogrammer** [comment]
@airesvsg 

http://example.com/wp-json/wp/v2/posts?_embed

this should be your refference link.

deactivate the plugin and take the response of the query save it, and activate the plugin again take the response of the query. then compare them in the posts there must be a _embeded child, in the _embeded child there must be wp:featuredmedia child. compare them please. When the plugin active there is recursion.

Best Regards
