### ISSUE TITLE
not work for endpoint with _embed

### ISSUE THREAD

**Issue by sjjianshen** [airesvsg/wp-rest-api-cache#6]
Hi mate,  seems the cache not work for url with _embed, 
<img width="1298" alt="screen shot 2017-01-23 at 5 54 46 pm" src="https://cloud.githubusercontent.com/assets/9349921/22199298/3b95cadc-e195-11e6-9c00-a787f120c504.png">
It will embed itself in

Best Regards

**Comment by redprogrammer** [comment]
i wrote this before but the issue  closed, if you find any solution pls write me

**Comment by airesvsg** [comment]
Hi @redprogrammer,
Please, send me your files and database for my email (airesvsg@gmail.com).
Thanks

**Comment by airesvsg** [comment]
Hi @sjjianshen,
How did you solve this bug?
I didn't see any errors in my tests.
Thanks
