### ISSUE TITLE
Enabled but no time difference

### ISSUE THREAD

**Issue by MarkehMe** [airesvsg/wp-rest-api-cache#7]
For an API request to get all posts (/wp-json/wp/v2/posts) it takes around 4000ms. 

When I enable the plugin it has no time difference. I assumed with the cache enabled this would be instant - as it would cache?

Perhaps there is a step I'm missing with installation. 

**WP REST API**: 
Version 2.0-beta15

**WP REST API Cache**: 
Version 1.2.0

**Comment by airesvsg** [comment]
Hi @MarkehMe,
The constant **WP_DEBUG** is active?
Thanks
