### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by front-stream** [airesvsg/wp-rest-api-cache#8]
Hi airesvsg.

Is it possible to clear cache only for specific endpoints? I would like to clear cache immediately only for specific post types when I create new post or update existing.

**Comment by airesvsg** [comment]
Hi @front-stream,
At this moment you can use the filter `rest_cache_skip`.

How to use:

```PHP
add_filter( 'rest_cache_skip', function( $skip, $request_uri ) {
  $skip_request_uri = array(
    'resquest_uri_1',
    'resquest_uri_2',
  );

  if ( in_array( $request_uri, $skip_request_uri ) ) {
    $skip = true;
  }
  
  return $skip;
}, 10, 2 );
```
Thanks
